CREATE DATABASE QLNSPN
GO
USE QLNSPN
GO
CREATE TABLE NGUOIDUNG
( TAIKHOAN NVARCHAR(50) PRIMARY KEY,
  MATKHAU NVARCHAR(50) not null,
  CHUCDANH NVARCHAR(50) not null)
GO
CREATE TABLE NHANVIEN
( MANV NVARCHAR(50) PRIMARY KEY,
  TENNV NVARCHAR(100),
  NGAYSINH DATE,
  GIOITINH NVARCHAR(50),
  DIACHI NVARCHAR(50),
  SDT NVARCHAR(50),
  LUONG FLOAT)
  GO
 CREATE TABLE NHACUNGCAP
	 ( MANCC NVARCHAR(50) PRIMARY KEY,
	  TENNCC NVARCHAR(100),
	  DIACHI NVARCHAR(50),
	  SDT NVARCHAR(50))
	  GO
CREATE TABLE HANG
(MAHANG NVARCHAR(50) PRIMARY KEY,
 TENHANG NVARCHAR(100),
 SOLUONG int,
 DONVITINH NVARCHAR(50),
 DONGIA FLOAT)

	  GO
 CREATE TABLE PHIEUNHAP
	  ( MAPHIEUNHAP NVARCHAR(50) PRIMARY KEY,
	  MANCC NVARCHAR(50) FOREIGN KEY REFERENCES NHACUNGCAP(MANCC),
	  MANV NVARCHAR(50) FOREIGN KEY REFERENCES NHANVIEN(MANV),
	  NGAYNHAP DATE,
	  TONGTIEN FLOAT)
	  GO
 CREATE TABLE CHITIETPHIEUNHAP
	   (MAPHIEUNHAP NVARCHAR(50) FOREIGN KEY (MAPHIEUNHAP) REFERENCES PHIEUNHAP(MAPHIEUNHAP),
		MAHANG NVARCHAR(50) FOREIGN KEY REFERENCES HANG(MAHANG),
	    SOLUONG INT,
		GIANHAP FLOAT,
		PRIMARY KEY (MAPHIEUNHAP,MAHANG))
	   GO
CREATE TABLE PHIEUXUAT
	  ( MAPHIEUXUAT NVARCHAR(50) primary key,
	   MANV NVARCHAR(50) FOREIGN KEY REFERENCES NHANVIEN(MANV),
	   NGAYXUAT DATE)
GO
CREATE TABLE CHITIETPHIEUXUAT
( MAPHIEUXUAT NVARCHAR(50) FOREIGN KEY REFERENCES PHIEUXUAT(MAPHIEUXUAT),
  MAHANG NVARCHAR(50) FOREIGN KEY REFERENCES HANG(MAHANG),
  SOLUONG INT,
  primary key (MAPHIEUXUAT,MAHANG))
	   Go
 CREATE TABLE HOADON
	 ( MAHD NVARCHAR(50) PRIMARY KEY,
	  MANV NVARCHAR(50) FOREIGN KEY REFERENCES NHANVIEN(MANV),
	  NGAYLAP DATE not null default getdate(),
	  THANHTIEN FLOAT)	
	  GO
CREATE TABLE CHITIETHOADON
	 (MAHD NVARCHAR(50) FOREIGN KEY REFERENCES HOADON(MAHD),
	 MAHANG NVARCHAR(50) FOREIGN KEY REFERENCES HANG(MAHANG),
	 SOLUONG INT,
	 GIATIEN FLOAT,
	 primary key (MAHD,MAHANG))


	 ---------------------------------------------------------------------------------
SELECT GIATIEN FROM CHITIETHOADON Where MAHD = 'HD01'


--Thành tiền trong hóa đơn

	
--Xóa hóa đơn
	if exists (select count(*) from CHITIETHOADON where MAHD = 'HD03' group by MAHD having count(*) > 0)
	begin
		Delete CHITIETHOADON where MAHD = 'HD03'
		Delete HOADON where MAHD = 'HD03'
	end

--- Tính thành tiền cho từng hóa đơn
CREATE TRIGGER HD_ThanhTien ON CHITIETHOADON
FOR INSERT,UPDATE,DELETE
AS
begin
UPDATE HOADON
SET THANHTIEN = (SELECT SUM(GIATIEN)
                FROM CHITIETHOADON
				WHERE HOADON.MAHD=CHITIETHOADON.MAHD
				group by MAHD)
END

--Tính tổng tiền cho phiếu nhập
Create TRIGGER TONGTIEN_PN ON CHITIETPHIEUNHAP
FOR INSERT,UPDATE,DELETE
AS
BEGIN
UPDATE PHIEUNHAP
SET TONGTIEN=(SELECT SUM(CHITIETPHIEUNHAP.SOLUONG*GIANHAP)
              FROM CHITIETPHIEUNHAP,HANG
			  WHERE CHITIETPHIEUNHAP.MAHANG=HANG.MAHANG
			  AND CHITIETPHIEUNHAP.MAPHIEUNHAP=PHIEUNHAP.MAPHIEUNHAP
			  GROUP BY MAPHIEUNHAP)
END

---Cập nhật tổng số lượng hàng nhập vào kho
Create trigger Soluong_Hang on CHITIETPHIEUNHAP
FOR INSERT,UPDATE,DELETE
AS
BEGIN
UPDATE HANG
SET SOLUONG=(SELECT SUM(SOLUONG)
             FROM CHITIETPHIEUNHAP
			 WHERE CHITIETPHIEUNHAP.MAHANG=HANG.MAHANG
			 GROUP BY MAHANG)
END

--Cập nhật số lượng còn trong kho khi đã xuất hàng
CREATE TRIGGER RE_SOLUONG_HANG ON CHITIETPHIEUXUAT
FOR INSERT,UPDATE,DELETE
AS
BEGIN 
	DECLARE @MAHANG NVARCHAR(50)
	SELECT @MAHANG=MAHANG FROM inserted
	DECLARE @SOLUONG int
	SELECT @SOLUONG=SOLUONG FROM inserted
	UPDATE HANG
	SET SOLUONG=SOLUONG-@SOLUONG
	WHERE MAHANG=@MAHANG
END 

---Tính doanh thu theo tháng
 SELECT (SELECT SUM(THANHTIEN) FROM HOADON WHERE MONTH(HOADON.NGAYLAP) = 10 AND YEAR(HOADON.NGAYLAP) = 2023) -
       (SELECT SUM(TONGTIEN) FROM PHIEUNHAP WHERE MONTH(PHIEUNHAP.NGAYNHAP) = 10 AND YEAR(PHIEUNHAP.NGAYNHAP) = 2023) AS 'DOANH THU THANG'
---Tính doanh thu theo năm
SELECT (SELECT SUM(THANHTIEN) FROM HOADON WHERE YEAR(HOADON.NGAYLAP) = 2023) -
       (SELECT SUM(TONGTIEN) FROM PHIEUNHAP WHERE YEAR(PHIEUNHAP.NGAYNHAP) = 2023) AS 'DOANH THU NAM'

--Tính số lượng 
SELECT Thang as Thang, SUM(TongTienHoaDon) - SUM(TongTienPhieuNhap) as TongTien
FROM
(
SELECT MONTH(NgayLap) as Thang, SUM(ThanhTien) as TongTienHoaDon, 0 as TongTienPhieuNhap
FROM HOADON
WHERE YEAR(NgayLap) = 2023
GROUP BY MONTH(NgayLap)

UNION ALL--KẾT HỢP CÁC CÂU LỆNH SQL VỚI NHAU


SELECT MONTH(NgayNhap) as Thang, 0 as TongTienHoaDon, SUM(TongTien) as TongTienPhieuNhap
FROM PHIEUNHAP
WHERE YEAR(NgayNhap) = 2023
GROUP BY MONTH(NgayNhap)
) as TONGTIENTUNGBANG--DAT TEN BANG CHO TRUY VAN CON
GROUP BY Thang